# Name of your application. Used to uniquely configure containers.
service: kamal-blog

# Name of the container image.
image: abratashov/kamal-blog

# Deploy to these servers.
servers:
  - 31.42.190.196

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: abratashov

  # Always use an access token rather than real password when possible.
  password:
    - DOCKER_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  clear:
    DB_HOST: 31.42.190.196
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_PASSWORD

# Use accessory services (secrets come from .env).
accessories:
  db:
    image: postgres:15
    host: 31.42.190.196
    port: 5432
    env:
      clear:
        POSTGRES_USER: 'root'
      secret:
        - DATABASE_PASSWORD
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data
